### ISSUE TITLE
Plan to make it into a Python package?

### ISSUE THREAD

**Issue by ekzhu** [madelonhulsebos/sherlock#1]
Thanks for sharing this code base! Is there any plan for making this into a Python package available for installation? e.g. `pip install sherlock`

**Comment by madelonhulsebos** [comment]
Hi @ekzhu,

Thanks for sharing your request!
There are certainly plans for publishing Sherlock as a package ready for installation through pip.
The repository will be updated from [here](https://github.com/mitmedialab/sherlock-project).

Madelon

**Comment by ekzhu** [comment]
Awesome thanks!
