### ISSUE TITLE
Can you archive or remove?

### ISSUE THREAD

**Issue by dav-ell** [madelonhulsebos/sherlock#8]
This repository is currently linked directly by https://sherlock.media.mit.edu/, and is incorrect, as noted by the tiny link at the bottom of the README. The code in this repository is horribly inefficient and out of date (understandably so, since the updated code is in the new repository, here: https://github.com/mitmedialab/sherlock-project). 

This wouldn't be a problem, except that it's very hard to distinguish between the two when cloning and working with the code. To prove my point, the number of stars on this repository (32) is higher than the number of stars on the correct one (28), as of writing this. It's also not clear from the README that this repository is as out of date as it is. It has caused me more than a little frustration, and I'd like to avoid that for others as well.

Any chance that you could "archive" the repository and leave a clear note in the description at the top, and in the README, and tell people to go to the other one? I'm assuming you can't change the link on the MIT page. If you can do that, that'd of course be preferable, in addition to archiving or deleting this one.

Thanks very much!

**Comment by madelonhulsebos** [comment]
Thanks for raising this issue @dav-ell. I think it's a good suggestion, I will archive this repository after having revised the linked repository from https://sherlock.media.mit.edu/.
